name: ESLint static code analysis for backend 
on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 16

jobs:
  build:
    name: ESLint check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Checking code formatting
        run: npm run check